/** Settings icons — lucide-react re-exports kept in one place. */
import {
  User as UserIcon,
  Bot as BotIcon,
  Plug as PlugIcon,
  Palette as PaletteIcon,
  Shield as ShieldIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Monitor as MonitorIcon,
  Download as DownloadIcon,
  Trash2 as Trash2Icon,
  LogOut as LogOutIcon,
  Pencil as PencilIcon,
  Check as CheckIcon,
  X as XIcon,
  Globe as GlobeIcon,
  Sparkles as SparklesIcon,
  Cable as CableIcon,
  ExternalLink as ExternalLinkIcon,
} from "lucide-react";

export {
  UserIcon,
  BotIcon,
  PlugIcon,
  PaletteIcon,
  ShieldIcon,
  SunIcon,
  MoonIcon,
  MonitorIcon,
  DownloadIcon,
  Trash2Icon,
  LogOutIcon,
  PencilIcon,
  CheckIcon,
  XIcon,
  GlobeIcon,
  SparklesIcon,
  CableIcon,
  ExternalLinkIcon,
};
